### ISSUE TITLE
Cross-compiling from MacOS to x86_64-linux-musl

### ISSUE THREAD

**Issue by dandxy89** [rust-or/highs-sys#2] opened 2021-03-23 17:47 UTC
Hello @rust-or/owners ,

Have you of you attempted to create an AWS Lambda using the library?

**Comment by lovasoa** [comment] 2021-03-23 18:35
Ok, I transferred the issue to the highs-sys repository.

I think the problem is that highs-sys links highs itself dynamically, but it links libstdc++ dynamically, and your target doesn't have a libstdc++

https://github.com/rust-or/highs-sys/blob/master/build.rs#L55

**Comment by lovasoa** [comment] 2021-03-23 18:38
Are you interested in working on this issue ? Could you make a PR that detects whether libstdc++ should be statically linked and sets the right values in build.rs ? You could also update the CI to add a linux musl target.

**Comment by dandxy89** [comment] 2021-03-23 18:41
I can certainly give it a go. 

Thanks for the quick investigation - wish I had flagged it several days ago now to be fair. 

Many thanks @lovasoa

**Comment by lovasoa** [comment] 2021-03-23 18:55
I'm not an expert with C++ and CMake, but it looks like it has a useful option to add standard library linker flags:
https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_STANDARD_LIBRARIES.html

So you should be  able to add

```
        .define("CMAKE_CXX_STANDARD_LIBRARIES", "-static-libgcc -static-libstdc++")
```

to the build script.


Of course you will need to have a `libstdc++.a` for static linking to succeed.

**Comment by lovasoa** [comment] 2021-03-23 18:57
If you have a linux system lying around, I'd advise you try to get it working without cross-compilation first (just creating a fully statically linked binary from linux), then check if it cross-compiles correctly.

**Comment by lovasoa** [comment] 2021-03-23 19:38
libstdc++ should indeed probably be statically linked, but your initial issue may not be with that.

See https://github.com/rust-lang/rust/issues/36710

and the suggested workaround, using docker: https://github.com/rust-rocksdb/rust-rocksdb/issues/440#issuecomment-704959749

**Comment by dandxy89** [comment] 2021-06-04 15:53
Hey @lovasoa 

Managed to get hold of a Linux machine but unable to `build`.

```
~/highs-sys(master) » cargo build                                                                                                                                101 ↵ dan@dan-Galago-UltraPro
   Compiling highs-sys v0.1.4 (/home/dan/highs-sys)
error: failed to run custom build command for `highs-sys v0.1.4 (/home/dan/highs-sys)`

Caused by:
  process didn't exit successfully: `/home/dan/highs-sys/target/debug/build/highs-sys-064c0f4b45f3275d/build-script-build` (exit code: 101)
  --- stdout
  running: "cmake" "/home/dan/highs-sys/HiGHS" "-DFAST_BUILD=ON" "-DSHARED=OFF" "-DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDLL" "-DCMAKE_CXX_STANDARD_LIBRARIES=-static-libgcc -static-libstdc++" "-DCMAKE_INSTALL_PREFIX=/home/dan/highs-sys/target/debug/build/highs-sys-8fd57449c0e17be3/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Debug"
  -- Linking with OpenMP... 
  -- FAST_BUILD set to on.
   Note: The HiGHS team is preparing for our first official release. If you
         experience any issues please let us know via email or on GitHub.
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /home/dan/highs-sys/target/debug/build/highs-sys-8fd57449c0e17be3/out/build
  running: "cmake" "--build" "." "--target" "install" "--config" "Debug" "--"
  Consolidate compiler generated dependencies of target libhighs
  [ 80%] Built target libhighs
  Consolidate compiler generated dependencies of target highs
  [ 81%] Building CXX object app/CMakeFiles/highs.dir/__/src/mip/HighsDynamicRowMatrix.cpp.o
  app/CMakeFiles/highs.dir/build.make:131: recipe for target 'app/CMakeFiles/highs.dir/__/src/mip/HighsDynamicRowMatrix.cpp.o' failed
  CMakeFiles/Makefile2:141: recipe for target 'app/CMakeFiles/highs.dir/all' failed
  Makefile:145: recipe for target 'all' failed

  --- stderr
  CMake Warning (dev) in CMakeLists.txt:
    Policy CMP0110 is not set: add_test() supports arbitrary characters in test
    names.  Run "cmake --help-policy CMP0110" for policy details.  Use the
    cmake_policy command to set the policy and suppress this warning.

    The following name given to add_test() is invalid if CMP0110 is not set or
    set to OLD:

      `25fv47 ´

  This warning is for project developers.  Use -Wno-dev to suppress it.

  CMake Warning (dev) in CMakeLists.txt:
    Policy CMP0110 is not set: add_test() supports arbitrary characters in test
    names.  Run "cmake --help-policy CMP0110" for policy details.  Use the
    cmake_policy command to set the policy and suppress this warning.

    The following name given to add_test() is invalid if CMP0110 is not set or
    set to OLD:

      `80bau3b ´

  This warning is for project developers.  Use -Wno-dev to suppress it.

  CMake Warning (dev) in CMakeLists.txt:
    Policy CMP0110 is not set: add_test() supports arbitrary characters in test
    names.  Run "cmake --help-policy CMP0110" for policy details.  Use the
    cmake_policy command to set the policy and suppress this warning.

    The following name given to add_test() is invalid if CMP0110 is not set or
    set to OLD:

      `greenbea ´

  This warning is for project developers.  Use -Wno-dev to suppress it.

  CMake Warning (dev) in CMakeLists.txt:
    Policy CMP0110 is not set: add_test() supports arbitrary characters in test
    names.  Run "cmake --help-policy CMP0110" for policy details.  Use the
    cmake_policy command to set the policy and suppress this warning.

    The following name given to add_test() is invalid if CMP0110 is not set or
    set to OLD:

      `bgetam ´

  This warning is for project developers.  Use -Wno-dev to suppress it.

  CMake Warning (dev) in CMakeLists.txt:
    Policy CMP0110 is not set: add_test() supports arbitrary characters in test
    names.  Run "cmake --help-policy CMP0110" for policy details.  Use the
    cmake_policy command to set the policy and suppress this warning.

    The following name given to add_test() is invalid if CMP0110 is not set or
    set to OLD:

      `gas11 ´

  This warning is for project developers.  Use -Wno-dev to suppress it.

  In file included from /home/dan/highs-sys/HiGHS/src/mip/HighsDynamicRowMatrix.cpp:10:0:
  /home/dan/highs-sys/HiGHS/src/./mip/HighsDynamicRowMatrix.h:56:3: error: ‘size_t’ does not name a type
     size_t nonzeroCapacity() const { return ARvalue_.size(); }
     ^
  cc1plus: warning: unrecognized command line option ‘-Wno-unused-const-variable’
  cc1plus: warning: unrecognized command line option ‘-Wno-defaulted-function-deleted’
  make[2]: *** [app/CMakeFiles/highs.dir/__/src/mip/HighsDynamicRowMatrix.cpp.o] Error 1
  make[1]: *** [app/CMakeFiles/highs.dir/all] Error 2
  make: *** [all] Error 2
  thread 'main' panicked at '
  command did not execute successfully, got: exit code: 2
```

Are you able to advise / take a look at this at all?

**Closed** 2021-08-02 20:44 UTC
